package com.thg.gdeaws.db.model;
// Generated Sep 29, 2015 7:46:07 PM by Hibernate Tools 3.2.2.GA


import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="THG_DC_ACCOUNT"
    , uniqueConstraints = @UniqueConstraint(columnNames="ACCOUNT_NAME") 
)
@SuppressWarnings("serial") public class Account  implements java.io.Serializable {


     private Long accountId;
     private String accountName;
     private String description;
     private Boolean active;
     private Date createdOn;
     private String adminEmail;
     private Long badgeExpiryInMins;
     private Set<User> users = new HashSet<User>(0);

    public Account() {
    }

	
    public Account(String accountName, String adminEmail) {
        this.accountName = accountName;
        this.adminEmail = adminEmail;
    }
    public Account(String accountName, String description, Boolean active, Date createdOn, String adminEmail, Set<User> users) {
       this.accountName = accountName;
       this.description = description;
       this.active = active;
       this.createdOn = createdOn;
       this.adminEmail = adminEmail;
       this.users = users;
    }
   
    @SequenceGenerator(name="generator", sequenceName="THG_DC_ACCOUNT_SEQ")
    @Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    @Column(name="ACCOUNT_ID", unique=true, nullable=false, precision=22, scale=0)
    public Long getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }
    
    @Column(name="ACCOUNT_NAME", unique=true, nullable=false, length=200)
    public String getAccountName() {
        return this.accountName;
    }
    
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }
    
    @Column(name="DESCRIPTION", length=800)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="ACTIVE", precision=1, scale=0)
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    
    @Column(name="CREATED_ON", length=7)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    
    @Column(name="ADMIN_EMAIL", nullable=false, length=400)
    public String getAdminEmail() {
        return this.adminEmail;
    }
    
    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="account")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }

    @Column(name="BADGE_EXPIRY_IN_MINS", unique=true, nullable=false, precision=22, scale=0)
	public Long getBadgeExpiryInMins() {
		return this.badgeExpiryInMins;
	}


	public void setBadgeExpiryInMins(Long badgeExpiryInMins) {
		this.badgeExpiryInMins = badgeExpiryInMins;
	}


}


